version: '3.8'

services:
  ciudadela-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ciudadela-app
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Bogota
      # - SPRING_DATA_MONGODB_URI=TU_URI_AQUI # Puedes sobrescribir properties aquí si lo necesitas
    restart: unless-stopped
